# -*- coding: utf-8 -*-
"""Untitled55.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lEiV_NxvC0udk5OxiuWOEQeLgzdBSJJ0
"""

import requests
from bs4 import BeautifulSoup
import csv
!pip install newspaper3k
import newspaper
# Function to extract articles from a given URL
def extract_articles(url):
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')

    articles = []
    article = newspaper.Article(url=url, language='en')
    article.download()
    article.parse()
    article ={
        "title": article.title,
        "text": article.text,
        "published_date": article.publish_date,
        "keywords": article.keywords,
        "summary": article.summary
    }
    articles.append(article)

    return articles

# Example URLs
urls = [
    'https://www.cnbc.com/2024/01/05/florida-wins-first-fda-approval-to-import-drugs-from-canada.html',
    'https://www.cnbc.com/2024/01/04/ncaa-and-espn-ink-8-year-920-million-media-rights-deal.html',
    'https://www.cnbc.com/2024/01/05/coinbase-to-expand-crypto-derivatives-in-eu-with-license-acquisition-.html',
    'https://www.cnbc.com/2024/01/05/coinbase-gemini-plan-user-risk-assessments-in-uk-ahead-of-new-rules.html',
    'https://www.cnbc.com/2024/01/05/jobless-rate-for-black-americans-declines-to-5point2percent-to-end-2023-on-a-positive-note.html',
    'https://www.cnbc.com/2023/12/29/palo-alto-networks-hitting-100-billion-in-market-cap-is-the-beginning.html',
    'https://www.cnbc.com/2023/12/18/vans-owner-vf-corp-shares-tumble-after-cyberattack.html',
    'https://www.cnbc.com/2024/01/05/teen-used-savings-to-start-lucrative-amazon-side-hustle-guinealoft.html',
    'https://www.cnbc.com/2024/01/04/trump-received-at-least-7point8-million-in-payments-from-foreign-governments-as-president-house-democrats-say.html',
    'https://www.cnbc.com/2023/12/27/houthi-attacks-us-strikes-spur-concerns-of-wider-mideast-conflict.html',
    'https://www.cnbc.com/2023/12/27/vivek-ramaswamys-campaign-stops-all-tv-ad-spending-less-than-a-month-before-iowa-and-new-hampshire.html',
    'https://www.cnbc.com/2023/12/22/supreme-court-sidesteps-decision-on-trump-presidential-immunity-claim-in-federal-election-interference-case-.html',
    'https://www.cnbc.com/2023/12/20/us-releases-maduro-ally-alex-saab-to-venezuela-for-americans.html',
    'https://www.cnbc.com/2023/12/19/us-bank-fined-36-million-for-frozen-unemployment-benefits.html',
    'https://www.cnbc.com/2023/12/19/white-house-announces-new-steps-toward-launching-its-climate-corps-for-young-people.html',
    'https://www.cnbc.com/2023/12/11/man-threatened-to-kill-gop-presidential-candidate-vivek-ramaswamy-doj.html',
    'https://www.cnbc.com/2023/12/06/former-speaker-kevin-mccarthy-to-resign-from-congress-at-year-end.html',
    'https://www.cnbc.com/2023/12/05/george-santos-special-election-set-for-feb-13.html',
    'https://www.cnbc.com/2023/12/05/former-researcher-alleges-harvard-forced-her-out-to-preserve-facebook-donations-.html',
    'https://www.cnbc.com/2023/12/04/former-us-ambassador-spied-for-cuba-for-decades-doj.html'
    # Add more URLs as needed
]

# Extract articles from each URL
all_articles = []
for url in urls:
    all_articles.extend(extract_articles(url))

# Save articles to CSV
csv_file_path = 'aa.csv'
fields = ['title', 'text', 'summary', 'keywords','published_date']

with open(csv_file_path, 'w', newline='', encoding='utf-8') as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=fields)
    writer.writeheader()
    writer.writerows(all_articles)

